[tool.poetry]
name = "chef"
version = "0.1.0"
description = ""
authors = ["josef24 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^3.0.0"
names = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
